// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type AuthorRole struct {
	ID        uuid.UUID
	Name      sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Chat struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Title     sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Message struct {
	ID           uuid.UUID
	AuthorRoleID uuid.UUID
	Content      string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type User struct {
	ID        uuid.UUID
	FullName  string
	Email     string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
